name: My Test Repo Reporter

on:
  push:
    branches:
      - develop
      - stage
      - master

  # pull_request:
  #   branches:
  #     - development

  workflow_dispatch:

# concurrency:
#   group: build-and-deploy-${{ github.head_ref }}
#   cancel-in-progress: true

env:
  WORKFLOW_REPO_VARIABLE: ${{ vars.REPO_VARIABLE_NAME }}
  WORKFLOW_ENVIRONMENT: ${{ github.ref_name == 'master' && 'prod' || github.ref_name == 'develop' && 'development' || github.ref_name }}

jobs:
  reporter:
    name: Report the variables and secrets values
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'prod' || github.ref_name == 'develop' && 'development' || github.ref_name  }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: 8a235eaf-7bd0-43f8-8f55-f8c81457d5e4
          tenant-id: 833a9480-bdcd-4d3d-9f4e-d0a7d9814209
          subscription-id: 92c40ca0-a6b2-4b4d-a328-6d63fc4533ee

      - uses: azure/get-keyvault-secrets@v1
        id: get-kevault-secrets
        with:
          keyvault: ${{ vars.AZURE_KEY_VAULT_NAME }}
          secrets: ${{ vars.AZURE_KEY_VAULT_SECRET_NAME__FUNC_APP_PUBLISH_PROFILE }}

      - name: What are the secrets?
        run: echo ${{ steps.get-kevault-secrets.outputs.* }}

      - name: Echo report variable names
        run: |
          echo ${{ env.WORKFLOW_REPO_VARIABLE }}
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}
          echo ${{ env.WORKFLOW_ENVIRONMENT }}
          echo ${{ env.MY_ENVIRONMENT_VARIABLE }}
