name: My Test Repo Reporter

on:
  push:
    branches:
      - develop
      - stage
      - master

  pull_request:
    branches:
      - develop
      - stage
      - master

  workflow_dispatch:

concurrency:
  group: build-and-deploy-${{ github.head_ref }}
  cancel-in-progress: true

env:
  WORKFLOW_REPO_VARIABLE: ${{ vars.REPO_VARIABLE_NAME }}
  WORKFLOW_ENVIRONMENT: ${{ github.ref_name == 'master' && 'prod' || github.ref_name == 'develop' && 'development' || github.ref_name }}

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: A job to Say Hello
    steps:
      - name: Hello world action step
        id: hello-action-step
        uses: kurt-opel/github-action-hello-world@v1.1
        with:
          who-to-greet: BigDog63
      - name: Get the output time
        run: echo "The time was ${{ steps.hello-action-step.outputs.time }}."

  reporter:
    name: Report the variables and secrets values
    runs-on: windows-latest
    environment: ${{ github.ref_name == 'master' && 'prod' || github.ref_name == 'develop' && 'development' || github.ref_name  }}
    env:
      APP_PUBLISH_PROFILE: "" # will be populated later
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Echo event name
        run: echo ${{ github.event_name }}
        
      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     auth-type: IDENTITY
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     enable-AzPSSession: true
      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:
      #     # azcliversion: latest
      #     inlineScript: |
      #       az account show

      # - name: Azure PowerShell script
      #   uses: azure/powershell@v2
      #   with:
      #     azPSVersion: latest
      #     inlineScript: |
      #       Get-AzContext

      - name: Get secret from keyvault
        id: get-secret-from-keyvault
        shell: bash
        run: >
          gh_secret=$(az keyvault secret show 
          --name GitHub
          --vault-name kv-github-workflow-test
          --query value) &&
          echo "::add-mask::$gh_secret" &&
          echo "APP_PUBLISH_PROFILE=$gh_secret" >> $GITHUB_ENV

      - name: Output Secret Value
        env:
          ENV_GH_SECRET: ${{ env.APP_PUBLISH_PROFILE }}
        run: echo "SecretValue is $APP_PUBLISH_PROFILE"

      # - uses: azure/get-keyvault-secrets@v1
      #   id: get-kevault-secrets
      #   with:
      #     keyvault: ${{ vars.AZURE_KEY_VAULT_NAME }}
      #     secrets: ${{ vars.AZURE_KEY_VAULT_SECRET_NAME__FUNC_APP_PUBLISH_PROFILE }}

      # - name: What are the secrets?
      #   run: echo ${{ steps.get-kevault-secrets.outputs.* }}

      # - name: Echo report variable names
      #   run: |
      #     echo ${{ env.WORKFLOW_REPO_VARIABLE }}
      #     echo ${{ github.ref_name }}
      #     echo ${{ github.ref }}
      #     echo ${{ env.WORKFLOW_ENVIRONMENT }}
      #     echo ${{ env.MY_ENVIRONMENT_VARIABLE }}
