name: My Test Repo Reporter

on:
  push:
    branches:
      - develop
      - stage
      - master

  # pull_request:
  #   branches:
  #     - development

  workflow_dispatch:

# concurrency:
#   group: build-and-deploy-${{ github.head_ref }}
#   cancel-in-progress: true

env:
  WORKFLOW_REPO_VARIABLE: ${{ vars.REPO_VARIABLE_NAME }}
  WORKFLOW_ENVIRONMENT: ${{ github.ref_name == 'master' && 'prod' || github.ref_name == 'develop' && 'development' || github.ref_name }}

jobs:
  reporter:
    name: Report the variables and secrets values
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'prod' || github.ref_name == 'develop' && 'development' || github.ref_name  }}
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:
          azPSVersion: latest
          inlineScript: |
            Get-AzContext

      # - uses: azure/get-keyvault-secrets@v1
      #   id: get-kevault-secrets
      #   with:
      #     keyvault: ${{ vars.AZURE_KEY_VAULT_NAME }}
      #     secrets: ${{ vars.AZURE_KEY_VAULT_SECRET_NAME__FUNC_APP_PUBLISH_PROFILE }}

      # - name: What are the secrets?
      #   run: echo ${{ steps.get-kevault-secrets.outputs.* }}

      # - name: Echo report variable names
      #   run: |
      #     echo ${{ env.WORKFLOW_REPO_VARIABLE }}
      #     echo ${{ github.ref_name }}
      #     echo ${{ github.ref }}
      #     echo ${{ env.WORKFLOW_ENVIRONMENT }}
      #     echo ${{ env.MY_ENVIRONMENT_VARIABLE }}
