name: My Test Repo

on:
  push:
    branches:
      - development
      - master

  pull_request:
    branches:
      - development

  workflow_dispatch:

# concurrency:
#   group: build-and-deploy-${{ github.head_ref }}
#   cancel-in-progress: true

env:
  WORKFLOW_REPO_VARIABLE: ${{ vars.REPO_VARIABLE_NAME }}

jobs:
  setter:
    outputs:
      solution-version: ${{ steps.set-solution-version.outputs.SOLUTION_VERSION }}
    runs-on: ubuntu-latest
    name: Set some variables for later use
    steps:
      - uses: actions/checkout@v4

      - name: Set an ENV
        run: echo "FOO=bar" >> $GITHUB_ENV

      - name: get value from json
        if: success() || failure()
        id: json-properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: my-data.json
          prop_path: 'solution.version'

      - name: Show value from json
        if: success() || failure()
        run: |
          echo ${{ steps.json-properties.outputs.value }}

      - name: Set json value to output
        id: set-solution-version
        if: success() || failure()
        env:
          SOLUTION_VERSION_STEP_OUTPUT: ${{ steps.json-properties.outputs.value }}
        run: |
          echo "SOLUTION_VERSION=${{ env.SOLUTION_VERSION_STEP_OUTPUT }}" >> $GITHUB_OUTPUT
          echo ${{ env.SOLUTION_VERSION_STEP_OUTPUT }}

      - name: Show the set vars
        env:
          SOLUTION_VERSION: ${{ needs.setter.output.solution-version }}
        run: |
          echo ${{ env.FOO }}
          echo ${{ needs.setter.output.solution-version }}
          echo ${{ env.SOLUTION_VERSION }}

  reporter:
    name: Report the variables and secrets values
    runs-on: ubuntu-latest
    needs: setter
    env:
      SOLUTION_VERSION: ${{ needs.setter.outputs.solution-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Echo report variable name
        run: |
          echo ${{ env.WORKFLOW_REPO_VARIABLE }}
          echo ${{ needs.setter.outputs.solution-version }}
          echo ${{ env.SOLUTION_VERSION }}
