name: Report Values

run-name: Report Values - requested by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      is-true:
        description: It is true?
        required: true
        type: boolean
        default: false

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      run-extra: ${{ inputs.is-true }}
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Always Run
        run: echo "Base Build"

      - name: Runs if true
        if: ${{ inputs.is-true }}
        run: echo "It is true"
